name: 01 - Building Blocks
on: push
jobs:
 name: echo-hello
 runs-on: ubuntu-latest
 steps:
  - name: Say Hello
    run: echo "Hello, World!"
 name: echo-goodbye
 runs-on: ubuntu-latest
 steps:
  - name: failed step
    run: echo "failed"
         exit 1
  - name: say goodbye
    run: echo "Goodbye, World!"