
name: 01 - Building Blocks
on: push
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: success step
        run: |
          echo "success"
          exit 0
      - name: say goodbye
        run: echo "Goodbye, World!"